applications:
- name: token_msg
  memory: 512M
  instances: 1
  host: tm_e2e
  domain: cfapps.io
  command: bundle exec rake db:create db:migrate db:seed && bundle exec rails s
  env:
    RAILS_ENV: e2e
  services:
  - tm_psql