# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b375b609b09dcd5fee4495f6fe56d46e14baac7658ef6ecb75ced6f4e936959c9e0eed42900b32c951f9f9c32837890801688aadfc4ddd710f98287ee97cc9

test:
    secret_key_base: f0dbb43a58595427e5330a455600236ab01ec247c2607b0429a9cc6b90f888ecab6641f82d7b683b31342fa912ab3151259fa4dd4641a8689f249b951dfc425e

# Do not keep production secrets in the repository,
# instead read values from the environment.
e2e:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
